name: 'Deploy'
on:
  push:
    tags:
      - v*

env:
  S3_BUCKET_DEV: shc-verifier-services-dev
  S3_BUCKET_TEST: shc-verifier-services-test
  S3_BUCKET_PROD: shc-verifier-services-prod
  S3_DIR: vci-directory
  LOCAL_SOURCE_FILE: vci-issuers.json
  REGION: us-east-1
  ROLE_TO_ASSUME: arn:aws:iam::789379687343:role/GithubECSRole
  ROLE_SESSION_NAME: GithubActionsECSDev

jobs:
  deployDev:
    if: contains(github.ref, 'dev')
    name: 'Deploy VCI issuers list to TCP dev'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: 'Configure Dev AWS Role'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.REGION }}
        role-to-assume: ${{ env.ROLE_TO_ASSUME }}
        role-duration-seconds: 1200
        role-session-name: ${{ env.ROLE_SESSION_NAME }}
    - name: 'Sync issuers file to S3'
      run: |
        aws s3 sync . 's3://${{ env.S3_BUCKET_DEV }}/${{ env.S3_DIR }}' --exclude='*' --include='${{ env.LOCAL_SOURCE_FILE }}'

  deployTest:
    if: contains(github.ref, 'test')
    name: 'Deploy VCI issuers list to TCP test'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: 'Configure Test AWS Role'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.REGION }}
        role-to-assume: ${{ env.ROLE_TO_ASSUME }}
        role-duration-seconds: 1200
        role-session-name: ${{ env.ROLE_SESSION_NAME }}
    - name: 'Sync issuers file to S3'
      run: |
        aws s3 sync . 's3://${{ env.S3_BUCKET_TEST }}/${{ env.S3_DIR }}' --exclude='*' --include='${{ env.LOCAL_SOURCE_FILE }}'

  deployProd:
    if: contains(github.ref, '-prod')
    name: 'Deploy VCI issuers list to TCP production'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: 'Configure Prod AWS Role'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.REGION }}
        role-to-assume: ${{ env.ROLE_TO_ASSUME }}
        role-duration-seconds: 1200
        role-session-name: ${{ env.ROLE_SESSION_NAME }}
    - name: 'Sync issuers file to S3'
      run: |
        aws s3 sync . 's3://${{ env.S3_BUCKET_PROD }}/${{ env.S3_DIR }}' --exclude='*' --include='${{ env.LOCAL_SOURCE_FILE }}'