name: "Test Scripts"

on:
  pull_request_target:
    types: [opened, synchronize]
    paths-ignore:
      - 'vci-issuers*.json'
      - 'scripts/*.py'
      - '.github/workflows/test-scripts.yaml'
  push:
    branches:
      - main
    paths-ignore:
      - 'vci-issuers*.json'
      - 'scripts/*.py'
      - '.github/workflows/test-scripts.yaml'

jobs:
  runTests:
    name: "Test Scripts"
    runs-on: [ubuntu-latest]
    steps:
      - run: 'echo "No build required" '