name: "Validate Issuers File On Push"

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  runTests:
    name: "Validate Issuers File"
    runs-on: [ubuntu-latest]
    steps:
      - uses: "actions/checkout@v2"
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: 'head'

      - uses: "actions/checkout@v2"
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          path: 'base'

      - name: Cache Python venv
        uses: actions/cache@v2
        with:
          path: venv
          key: ${{ runner.os }}-build-${{ hashFiles('head/scripts/requirements.txt') }}

      - name: "Validate Issuers File"
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r head/scripts/requirements.txt
          cd head/scripts
          python validate_diffs.py ../vci-issuers.json ../../base/vci-issuers.json