name: VCI directory audit action
on:
  push:
    branches:
      - main
  schedule:
      - cron: '0 12 * * *'
jobs:
  vci-directory-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          npm install
          npm run build --if-present
      - run: |
          cd scripts/vci-directory-auditor
          npm run audit -- -o ../../logs/new_log.json -p ../../logs/daily_log.json -s ../../logs/daily_log_snapshot.json -a ../../logs/daily_audit.json -d ../../vci-issuers.json
          mv ../../logs/new_log.json ../../logs/daily_log.json
          npm run assemble -- -s ../../logs/vci_snapshot.json -c ../../logs/daily_log_snapshot.json
      - name: git check in
        env:
          GIT_OWNER_EMAIL: ${{ secrets.GIT_OWNER_EMAIL }}
          PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
        run: |
          git config user.email "$GIT_OWNER_EMAIL"
          git config user.name "misterzero"
          if [[ `git status --porcelain` ]]; then
            git add -f logs/daily_log.json
            git add -f logs/daily_log_snapshot.json
            git add -f logs/daily_audit.json
            git add -f logs/vci_snapshot.json
            git commit -a -m "daily dir and audit snapshot"
            git remote add myorigin https://misterzero:$PUSH_TOKEN@github.com/misterzero/vci-directory-auditor.git
            git push myorigin HEAD:main
          else
            echo 'no changes'
          fi
      - uses: actions/upload-artifact@v2
        with:
          name: save-log-files
          path: logs/*

      
  